// Sepay webhook receiver — auto-mark order paid when matching bank transaction arrives.
//
// Setup:
//   1. Sign up at https://my.sepay.vn (free 1000 tx/month)
//   2. Link Đại Long company bank account (Sepay reads via Internet Banking session)
//   3. Configure webhook → URL: https://gcjiiiijfeitomegnivd.supabase.co/functions/v1/sepay-webhook
//      Auth: API Key (set in Sepay dashboard) → matched against SEPAY_WEBHOOK_TOKEN env
//   4. Set Supabase Edge Function secrets:
//        supabase secrets set SEPAY_WEBHOOK_TOKEN=<generated by Sepay>
//        supabase secrets set SUPABASE_SERVICE_ROLE_KEY=<from project settings>
//
// Payload (Sepay docs):
//   {
//     id: 123, gateway: "MBBank", transactionDate: "2026-05-24 14:00:00",
//     accountNumber: "1234567890",
//     content: "DLABCDEFGH khach chuyen tien",
//     transferType: "in", transferAmount: 7500000,
//     code: "DLABCDEFGH" (auto-extracted by Sepay), referenceCode: "FT...",
//   }
//
// Matching logic:
//   - Extract DL[8 hex chars] from `code` field OR fallback regex on `content`
//   - Look up order WHERE substring(id::text, 1, 8) = lowercase(8 hex)
//   - Verify transferAmount === orders.sale_price
//   - UPDATE orders SET status='paid' (via approve_order then mark_paid OR direct)
//   - Existing trg_notify_order_status_change fires → dealer/supervisor inbox noti

// @ts-expect-error — Deno deploy runtime
import { createClient } from 'jsr:@supabase/supabase-js@2';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const SEPAY_TOKEN = Deno.env.get('SEPAY_WEBHOOK_TOKEN')!;

interface SepayPayload {
  id: number;
  gateway: string;
  transactionDate: string;
  accountNumber: string;
  content: string;
  transferType: 'in' | 'out';
  transferAmount: number;
  code: string | null;
  referenceCode: string;
}

const MEMO_PATTERN = /DL([0-9A-Fa-f]{8})/;

Deno.serve(async (req: Request) => {
  if (req.method !== 'POST') {
    return new Response('Method not allowed', { status: 405 });
  }

  // Verify Sepay auth — Sepay sends `Authorization: Apikey <token>`
  const auth = req.headers.get('authorization') ?? '';
  if (!auth.toLowerCase().startsWith('apikey ') || auth.slice(7) !== SEPAY_TOKEN) {
    return new Response('Unauthorized', { status: 401 });
  }

  let payload: SepayPayload;
  try {
    payload = await req.json();
  } catch {
    return new Response('Bad JSON', { status: 400 });
  }

  // Only process incoming transactions
  if (payload.transferType !== 'in') {
    return Response.json({ ignored: 'not_incoming', tx: payload.id });
  }

  // Extract memo
  const fromCode = payload.code && MEMO_PATTERN.exec(`DL${payload.code}`);
  const fromContent = MEMO_PATTERN.exec(payload.content ?? '');
  const memoMatch = (fromCode ?? fromContent)?.[1];
  if (!memoMatch) {
    return Response.json({ ignored: 'no_memo_match', tx: payload.id, content: payload.content });
  }
  const shortId = memoMatch.toLowerCase();

  const sb = createClient(SUPABASE_URL, SERVICE_ROLE, { auth: { persistSession: false } });

  // Find order by prefix match on UUID
  const { data: orders, error: findErr } = await sb
    .from('orders')
    .select('id, sale_price, status, dealer_id')
    .filter('id', 'gte', `${shortId}-0000-0000-0000-000000000000`)
    .filter('id', 'lt', `${shortId}-ffff-ffff-ffff-ffffffffffff`)
    .limit(2);

  if (findErr) {
    return Response.json({ error: findErr.message }, { status: 500 });
  }
  if (!orders || orders.length === 0) {
    return Response.json({ ignored: 'order_not_found', tx: payload.id, memo: shortId });
  }
  if (orders.length > 1) {
    return Response.json({ ignored: 'memo_ambiguous', tx: payload.id, memo: shortId, candidates: orders.length });
  }

  const order = orders[0];

  // Amount sanity check (allow ±1000đ rounding)
  if (Math.abs(Number(order.sale_price) - payload.transferAmount) > 1000) {
    return Response.json({
      ignored: 'amount_mismatch',
      tx: payload.id,
      order_id: order.id,
      expected: order.sale_price,
      received: payload.transferAmount,
    });
  }

  if (order.status === 'paid') {
    return Response.json({ ignored: 'already_paid', tx: payload.id, order_id: order.id });
  }
  if (order.status === 'rejected' || order.status === 'voided') {
    return Response.json({ ignored: `order_${order.status}`, tx: payload.id, order_id: order.id });
  }

  // Auto-approve if still pending (triggers calc_commission)
  if (order.status === 'pending') {
    const { error: appErr } = await sb
      .from('orders')
      .update({ status: 'approved', approved_at: new Date().toISOString() })
      .eq('id', order.id);
    if (appErr) return Response.json({ error: `approve failed: ${appErr.message}` }, { status: 500 });
  }

  // Mark paid (triggers notify_order_status_change → dealer + supervisor inbox)
  const { error: paidErr } = await sb
    .from('orders')
    .update({ status: 'paid' })
    .eq('id', order.id);
  if (paidErr) return Response.json({ error: `mark_paid failed: ${paidErr.message}` }, { status: 500 });

  // Stamp commission_payouts.paid_at + reference if commission row exists
  await sb
    .from('commission_payouts')
    .update({
      paid_at: new Date().toISOString(),
      payment_proof_url: `sepay:${payload.id}:${payload.referenceCode}`,
    })
    .eq('order_id', order.id);

  return Response.json({
    ok: true,
    tx: payload.id,
    order_id: order.id,
    amount: payload.transferAmount,
    gateway: payload.gateway,
  });
});
